services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: verdy_user
      POSTGRES_PASSWORD: verdy_pass
      POSTGRES_DB: verdy_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
